spring:
  datasource:
    url:
    username:
    password:
    initialization-mode: always
    dbcp2:
      validation-query: SELECT 1
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
jwt:
  secret:
  token-validity-in-seconds: 86400
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            BasicBinder: TRACE
